name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 22

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version: latest

      - name: Build frontend
        run: |
          bun install
          bun run build

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name "GitHub"
          git config --global user.email "<noreply@github.com>"
          SRC="$(pwd)"
          mkdir /tmp/github-pages && cd /tmp/github-pages
          git init . && git checkout --orphan "${BRANCH}"
          cp -r "${SRC}/${DEPLOY_DIR}"/* .
          [[ ! -z "${FQDN}" ]] && echo "${FQDN}" > CNAME
          touch .nojekyll
          git add . && git status && git commit --message "${MESSAGE}"
          git push -f -q "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "${BRANCH}"
        env:
          DEPLOY_DIR: frontend/build
          FQDN: openpulse.cocreators.ee
          MESSAGE: Deploy to GitHub Pages
          BRANCH: gh-pages
          GITHUB_TOKEN: ${{ github.token }}
